const langs = [
    'Italiano',
    'English',
    'Français',
    'Português',
    'Español',
    'Deutsch',
    'Ελληνικά',
	'український',
    'Nederlands',
    'العربية',
    'Pусский',
    'Български',
    'Slovenščina',
    'Türkçe',
    'Suomi',
    'Hrvatski',
    'српски',
    'Magyar'
  ];
const lang_codes = {
    'Italiano': 'it',
    'English': 'en',
    'Français': 'fr',
    'Português': 'pt',
    'Español': 'es',
    'Deutsch': 'de',
    'Ελληνικά': 'el',
	'український': 'uk',
    'Nederlands': 'nl',
    'العربية': 'ar',
    'Pусский': 'ru',
    'Български': 'bg',
    'Slovenščina': 'sl',
    'Türkçe': 'tr',
    'Suomi': 'fi',
    'Hrvatski': 'hr',
    'српски': 'sr',
    'Magyar': 'hu'
};
const lang_flags = [
	['it','Italiano','&#x1F1EE;&#x1F1F9;'],
	['en','English','&#x1F1EC;&#x1F1E7;'],
	['fr','Français','&#x1F1EB;&#x1F1F7;'],
	['pt','Português','&#x1F1F5;&#x1F1F9;'],
	['es','Español','&#x1F1EA;&#x1F1F8;'],
	['de','Deutsch','&#x1F1E9;&#x1F1EA;'],
	['el','Ελληνικά','&#x1F1EC;&#x1F1F7;'],
	['uk','Україна','&#x1F1FA;&#x1F1E6;'],
	['nl','Nederlands','&#x1F1F3;&#x1F1F1;'],
	['ar','العربية','&#x1F1F8;&#x1F1E6;'],
	['ru','Pусский','&#x1F1F7;&#x1F1FA;'],
	['bg','Български','&#x1F1E7;&#x1F1EC;'],
	['sl','Slovenščina','&#x1F1F8;&#x1F1EE;'],
	['tr','Türkçe','&#x1F1F9;&#x1F1F7;'],
	['fi','Suomi','&#x1F1EB;&#x1F1EE;'],
	['hr','Hrvatski','&#x1F1ED;&#x1F1F7;'],
	['sr','српски','&#x1F1F7;&#x1F1F8;'],
	['hu','Magyar','&#x1F1ED;&#x1F1FA;']
];
const t_menu = {
  'it': 'Menù',
  'en': 'Menu',
  'fr': 'Menu',
  'pt': 'Menu',
  'es': 'Menú',
  'de': 'Menü',
  'el': 'Μενού',
  'uk': 'Меню',
  'nl': 'Menu',
  'ar': 'قائمة',
  'ru': 'Меню',
  'bg': 'Меню',
  'sl': 'Menu',
  'tr': 'Menü',
  'fi': 'Valikko',
  'hr': 'Izbornik',
  'sr': 'Мени',
  'hu': 'Menü'
};
const t_history = {
  'it': 'archivio',
  'en': 'history',
  'fr': 'archive',
  'pt': 'arquívo',
  'es': 'archivo',
  'de': 'archiv',
  'el': 'αρχείο',
  'uk': 'архів',
  'nl': 'archief',
  'ar': 'أرشيف',
  'ru': 'архив',
  'bg': 'архив',
  'sl': 'arhiv',
  'tr': 'Arşiv',
  'fi': 'arkisto',
  'hr': 'arhiva',
  'sr': 'архива',
  'hu': 'archívum'
};
const t_reset = {
  'it': 'azzera',
  'en': 'reset',
  'fr': 'réinitialisation',
  'pt': 'reinicialização',
  'es': 'reinicio',
  'de': 'zurücksetzen',
  'el': 'επαναφορά',
  'uk': 'скидання',
  'nl': 'resetten',
  'ar': 'إعادة ضبط',
  'ru': 'перезагрузить',
  'bg': 'нулиране',
  'sl': 'resetirati',
  'tr': 'Sıfırla',
  'fi': 'nollaa',
  'hr': 'ponastaviti',
  'sr': 'ресетовати',
  'hu': 'Visszaállítás'
};
const t_param = {
  'it': 'parametri',
  'en': 'parameters',
  'fr': 'paramètres',
  'pt': 'parâmetros',
  'es': 'parámetros',
  'de': 'Parameter',
  'el': 'Παράμετροι',
  'uk': 'параметри',
  'nl': 'parameters',
  'ar': 'حدود',
  'ru': 'параметры',
  'bg': 'параметри',
  'sl': 'parametri',
  'tr': 'parametreler',
  'fi': 'parametrit',
  'hr': 'parametri',
  'sr': 'параметрима',
  'hu': 'paramétereket'
};
const t_language = {
  'it': 'lingua',
  'en': 'language',
  'fr': 'langue',
  'pt': 'língua',
  'es': 'idioma',
  'de': 'Sprache',
  'el': 'Γλώσσα',
  'uk': 'мова',
  'nl': 'taal',
  'ar': 'لغة',
  'ru': 'язык',
  'bg': 'език',
  'sl': 'jezik',
  'tr': 'dil',
  'fi': 'Kieli',
  'hr': 'Jezik',
  'sr': 'Језик',
  'hu': 'nyelv'
};
const t_key = {
  'it': 'codice API',
  'en': 'API key',
  'fr': 'code API',
  'pt': 'código API',
  'es': 'código API',
  'de': 'API-Schlüssel',
  'el': 'Κλειδί API',
  'uk': 'ключ API',
  'nl': 'API sleutel',
  'ar': 'مفتاح API',
  'ru': 'ключ API',
  'bg': 'API ключ',
  'sl': 'API ključ',
  'tr': 'API anahtarı',
  'fi': 'API-avain',
  'hr': 'API ključ',
  'sr': 'АПИ код',
  'hu': 'API kód'
};
const t_help = {
  'it': 'aiuto',
  'en': 'help',
  'fr': 'aide',
  'pt': 'ajuda',
  'es': 'ayuda',
  'de': 'Hilfe',
  'el': 'βοήθεια',
  'uk': 'довідка',
  'nl': 'hulp',
  'ar': 'يساعد',
  'ru': 'помощь',
  'bg': 'помогне',
  'sl': 'pomoč',
  'tr': 'yardım',
  'fi': 'auta',
  'hr': 'Pomozite',
  'sr': 'помоћ',
  'hu': 'Segítség'
};
const t_write = {
  'it': 'Scrivi qualcosa!',
  'en': 'Write something!',
  'fr': 'Écris quelque chose!',
  'pt': 'Escreva alguma coisa',
  'es': '¡Escribe algo!',
  'de': 'Schreibe etwas!',
  'el': 'Γράψε κάτι!',
  'uk': 'Напишіть щось!',
  'nl': 'Schrijf iets!',
  'ar': 'أكتب شيئا!',
  'ru': 'Напиши что-нибудь!',
  'bg': 'Напиши нещо!',
  'sl': 'Napisati nekaj!',
  'tr': 'Bir şey yaz!',
  'fi': 'Kirjoittaa jotain!',
  'hr': 'Napisati nešto!',
  'sr': 'Написати нешто!',
  'hu': 'Írjon valamit!'
};
const t_getapi = {
  'it': 'Devi ottenere il codice API presso platform.openai.com/overview',
  'en': 'You have to get your API key from platform.openai.com/overview',
  'fr': 'Vous devez obtenir votre clé API à partir de platform.openai.com/overview',
  'pt': 'Pode obter a chave API no platform.openai.com/overview',
  'es': 'Tienes que obtener tu clave API de platform.openai.com/overview',
  'de': 'Sie müssen Ihren API-Schlüssel von erhalten platform.openai.com/overview',
  'el': 'Πρέπει να λάβετε το κλειδί API από platform.openai.com/overview',
  'uk': 'Ви повинні отримати свій ключ API з platform.openai.com/overview',
  'nl': 'U moet uw API-sleutel ophalen van platform.openai.com/overview',
  'ar': 'يجب عليك الحصول على مفتاح API الخاص بك من platform.openai.com/overview',
  'ru': 'Вы должны получить ключ API от platform.openai.com/overview',
  'bg': 'Трябва да получите вашия API ключ от platform.openai.com/overview',
  'sl': 'Ključ API morate dobiti pri platform.openai.com/overview',
  'tr': 'API anahtarınızı şu adresten almanız gerekir: platform.openai.com/overview',
  'fi': 'Sinun on hankittava API-avain osoitteesta platform.openai.com/overview',
  'hr': 'Morate dobiti svoj API ključ od platform.openai.com/overview',
  'sr': 'Морате да добијете свој АПИ кључ од platform.openai.com/overview',
  'hu': 'Az API-kulcsot innen kell beszereznie platform.openai.com/overview'
};
const t_date = {
  'it': 'Data',
  'en': 'Date',
  'fr': 'Date',
  'pt': 'Data',
  'es': 'Fecha',
  'de': 'Datum',
  'el': 'Ημερομηνία',
  'uk': 'Дата',
  'nl': 'Datum',
  'ar': 'تاريخ',
  'ru': 'Дата',
  'bg': 'Дата',
  'sl': 'Datum',
  'tr': 'Tarih',
  'fi': 'Päivämäärä',
  'hr': 'Datum',
  'sr': 'Датум',
  'hu': 'Dátum'
};
const t_question = {
  'it': 'Domanda',
  'en': 'Question',
  'fr': 'Question',
  'pt': 'Pergunta',
  'es': 'Pregunta',
  'de': 'Frage',
  'el': 'Ερώτηση',
  'uk': 'Питання',
  'nl': 'Vraag',
  'ar': 'سؤال',
  'ru': 'Вопрос',
  'bg': 'Въпрос',
  'sl': 'vprašanje',
  'tr': 'Soru',
  'fi': 'Kysymys',
  'hr': 'Pitanje',
  'sr': 'Питање',
  'hu': 'Kérdés'
};
const t_answer = {
  'it': 'Risposta',
  'en': 'Answer',
  'fr': 'Reponse',
  'pt': 'Resposta',
  'es': 'Respuesta',
  'de': 'Antworten',
  'el': 'Απάντηση',
  'uk': 'Відповідь',
  'nl': 'Antwoord',
  'ar': 'إجابة',
  'ru': 'Отвечать',
  'bg': 'Отговор',
  'sl': 'Odgovori',
  'tr': 'Cevap',
  'fi': 'Vastaus',
  'hr': 'Odgovor',
  'sr': 'Одговор',
  'hu': 'Válasz'
};
const t_yourkey = {
  'it': 'Il tuo codice API da ChatGPT',
  'en': 'Your ChatGPT API key',
  'fr': 'Votre clé API ChatGPT',
  'pt': 'Tu clave API de ChatGPT',
  'es': 'Tu clave API de ChatGPT',
  'de': 'Ihr ChatGPT-API-Schlüssel',
  'el': 'Το κλειδί σας ChatGPT API',
  'uk': 'Ваш ключ API ChatGPT',
  'nl': 'Uw ChatGPT API-sleutel',
  'ar': 'مفتاح ChatGPT API الخاص بك',
  'ru': 'Ваш API-ключ ChatGPT',
  'bg': 'Вашият ключ за API на ChatGPT',
  'sl': 'Vaš ključ API ChatGPT',
  'tr': 'ChatGPT API anahtarınız',
  'fi': 'ChatGPT API -avaimesi',
  'hr': 'ChatGPT API anahtarınız',
  'sr': 'Ваш ЦхатГПТ АПИ кључ',
  'hu': 'Az Ön ChatGPT API-kulcsa'
};
const t_apinotvalid = {
  'it': 'Codice API non valido',
  'en': 'API key not valid',
  'fr': 'Le code API n\'est pas valid',
  'pt': 'Código API não válido',
  'es': 'Clave de API no válida',
  'de': 'API-Schlüssel ungültig',
  'el': 'Το κλειδί API δεν είναι έγκυρο',
  'uk': 'ключ API недійсний',
  'nl': 'API-sleutel niet geldig',
  'ar': 'مفتاح API غير صالح',
  'ru': 'Ключ API недействителен',
  'bg': 'API ключът не е валиден',
  'sl': 'Ključ API ni veljaven',
  'tr': 'API anahtarı geçerli değil',
  'fi': 'API-avain ei kelpaa',
  'hr': 'API ključ nije valjan',
  'sr': 'АПИ кључ није важећи',
  'hu': 'Az API kulcs érvénytelen'
};
const t_dbaserr = {
  'it': 'Errore base dati',
  'en': 'Database error',
  'fr': 'Erreur de la base de données',
  'pt': 'Erro base de dados',
  'es': 'Error de la base de dato',
  'de': 'Datenbankfehler',
  'el': 'Σφάλμα βάσης δεδομένων',
  'uk': 'Помилка бази даних',
  'nl': 'Datenbankfehler',
  'ar': 'خطأ في قاعدة البيانات',
  'ru': 'ошибка базы данных',
  'bg': 'грешка в базата данни',
  'sl': 'Napaka baze podatkov',
  'tr': 'veri tabanı hatası',
  'fi': 'tietokanta virhe',
  'hr': 'Pogreška baze podataka',
  'sr': 'грешка у датотеци',
  'hu': 'Adatbázis hiba'
};
const t_apisaved = {
  'it': 'Codice API registrato',
  'en': 'API key saved',
  'fr': 'Code API enregistré',
  'pt': 'Código API gravado',
  'es': 'Código API registrado',
  'de': 'Registrierter API-Code',
  'el': 'Εγγεγραμμένος κωδικός API',
  'uk': 'ключ API збережено',
  'nl': 'Geregistreerde API-code',
  'ar': 'تم تسجيل مفتاح API',
  'ru': 'Ключ API записан',
  'bg': 'API ключът е записан',
  'sl': 'Ključ API posnet',
  'tr': 'API anahtarı kaydedildi',
  'fi': 'API-avain tallennettu',
  'hr': 'API ključ spremljen',
  'sr': 'Регистровани АПИ код',
  'hu': 'Regisztrált API kód'
};
const t_ok = {
  'it': 'Va bene',
  'en': 'OK',
  'fr': 'D\'accord',
  'pt': 'Proceder',
  'es': 'De acuerdo',
  'de': 'OK',
  'el': 'Εντάξει',
  'uk': 'В порядку',
  'nl': 'OK',
  'ar': 'نعم',
  'ru': 'Хорошо',
  'bg': 'Добре',
  'sl': 'V redu',
  'tr': 'Tamam',
  'fi': 'OK',
  'hr': 'U redu',
  'sr': 'OK',
  'hu': 'Rendben'
};
const t_cancel = {
  'it': 'Annulla',
  'en': 'Cancel',
  'fr': 'Annuler',
  'pt': 'Cancelar',
  'es': 'Cancelar',
  'de': 'Stornieren',
  'el': 'Ματαίωση',
  'uk': 'Скасувати',
  'nl': 'Annuleren',
  'ar': 'يلغي',
  'ru': 'Отмена',
  'bg': 'Отказ',
  'sl': 'Prekliči',
  'tr': 'İptal etmek',
  'fi': 'Peruuttaa',
  'hr': 'Otkazati',
  'sr': 'Поништити',
  'hu': 'Megszünteti'
};
const t_norisp = {
  'it': 'Non risponde, prova più tardi per favore',
  'en': 'No answer, please try later',
  'fr': 'Ne repons pas, essaye plu tard svp',
  'pt': 'Não responde, tente mais tarde por favor',
  'es': 'No hay respuesta, intente más tarde',
  'de': 'Keine Antwort, bitte versuchen Sie es später',
  'el': 'Καμία απάντηση, δοκιμάστε αργότερα',
  'uk': 'Немає відповіді, спробуйте пізніше',
  'nl': 'Geen antwoord, probeer het later',
  'ar': 'لا إجابة ، يرجى المحاولة لاحقًا',
  'ru': 'Нет ответа, попробуйте позже',
  'bg': 'Няма отговор, моля, опитайте по-късно',
  'sl': 'Ni odgovora, poskusite pozneje',
  'tr': 'Cevap yok, lütfen daha sonra deneyin',
  'fi': 'Ei vastausta, yritä myöhemmin',
  'hr': 'Nema odgovora, pokušajte kasnije',
  'sr': 'Нема одговора, покушајте касније',
  'hu': 'Nincs válasz, próbálkozzon később'
};
const t_theme = {
  'it': 'grafica',
  'en': 'theme',
  'fr': 'graphique',
  'pt': 'gráfica',
  'es': 'grafica',
  'de': 'thema',
  'el': 'θέμα',
  'uk': 'тема',
  'nl': 'thema',
  'ar': 'سمة',
  'ru': 'тема',
  'bg': 'тема',
  'sl': 'tema',
  'tr': 'tema',
  'fi': 'teema',
  'hr': 'tema',
  'sr': 'тема',
  'hu': 'téma'
};
const t_models = {
  'it': 'modelli',
  'en': 'models',
  'fr': 'modèles',
  'pt': 'modelos',
  'es': 'modelos',
  'de': 'modelle',
  'el': 'μοντέλα',
  'uk': 'моделі',
  'nl': 'modellen',
  'ar': 'عارضات ازياء',
  'ru': 'модели',
  'bg': 'модели',
  'sl': 'modeli',
  'tr': 'modeller',
  'fi': 'mallit',
  'hr': 'modeli',
  'sr': 'модели',
  'hu': 'modellek'
};
const t_update = {
  'it': 'Aggiorna',
  'en': 'Update',
  'fr': 'Mise à jour',
  'pt': 'Actualização',
  'es': 'Actualización',
  'de': 'Aktualisierung',
  'el': 'Ανημέρωση',
  'uk': 'Оновити',
  'nl': 'Update',
  'ar': 'تحديث',
  'ru': 'Обновление',
  'bg': 'Актуализация',
  'sl': 'Posodobi',
  'tr': 'Güncelleme',
  'fi': 'Päivittää',
  'hr': 'Ažuriraj',
  'sr': 'Aжурирање',
  'hu': 'Frissítés'
};
